hl.on("hyprland.start", function()
	hl.exec_cmd("fcitx5")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("/usr/lib/kdeconnectd")
	hl.exec_cmd("darkman run")
	hl.exec_cmd("gdbus wait --session org.kde.StatusNotifierWatcher && dex -a -s ~/.config/autostart/")
end)
