Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Net/CursorBlinkTime 1000
Net/CursorBlink 1
Gtk/CursorThemeSize 24
Net/SoundThemeName "freedesktop"
Gtk/FontName "Google Sans Flex, Medium 11"
Net/ThemeName "adw-gtk3"
Net/IconThemeName "breeze-plus"
Gtk/CursorThemeName "Bibata-Modern-Classic"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Gdk/UnscaledDPI 98304
Gdk/WindowScalingFactor 2
